{
  "hash": "4fef4c0ccf8699175e0c1266d5ad7096",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Generalize Fast!\"\nsubtitle: \"Replication data from experiment: \n*Social Competition Drives Collective Action to Reduce Informal Waste Burning in Uganda*\"\nauthor: \"**EDS 241**\"\ndate: \"2026-01-15\"\nformat: html\nexecute:\n  execute-dir: project\n---\n### Map of Treatment Assignment Zones in Nansana, Uganda \n\n![](images/S5_Buntaine24.png)\n\n    * SOURCE: Figure from Buntaine et al., 2024 (S5; Supplemental Materials)\n\n### Open source data & applied study:\n\nOpen access data was utilized for this class exercise from the study (Buntaine et al., 2024):\n\n> Buntaine, M. T., Komakech, P., & Shen, S. V. (2024). *Social competition drives collective action to reduce informal waste burning in Uganda*. Proceedings of the National Academy of Sciences, 121(23). https://doi.org/10.1073/pnas.2319712121\n\n\n### Goals of this exercise\n\n1.  Start with a simple OLS model\n\n2.  Demonstrate the rationale for estimating progressively complex models\n\n3.  Illustrate a causal inference approach (i.e., identify `robust` estimators)\n\n4. Conclusion: What is the take-home message of the Lab-1 exercise? . . .\n\n    Estimating complex models is a relatively easy part of our work as data scientists...\n\n    * Making informed specification decisions & communicating results is the hard part\n    (i.e., the science side of `data science`)!  \n    \n### Let's get started!\n\nLoad packages and data: \n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)   # Keeping things tidy \nlibrary(janitor)     # Housekeeping \nlibrary(here)        # Location, location, location \n#install.packages(\"jtools\")\nlibrary(jtools)      # Pretty regression output \nlibrary(gt)          # Tables \nlibrary(gtsummary)   # Table for checking balance \n#install.packages(\"performance\")\nlibrary(performance) # Check model diagnostics \n#install.packages(\"see\") # Visualization engine for performance package\n#install.packages(\"huxtable\") # Package required for export_summs\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in waste pile count data\ncounts_gpx <- read_csv(here::here(\"course-materials\", \"labs\", \"data\", \"waste_pile_counts_gpx.csv\")) %>% \n    rename(\"waste_piles\" = \"total\",\n           \"rain_0_48hrs\" = \"rf_0_to_48_hours\",\n           \"rain_49_168hrs\" = \"rf_49_to_168_hours\") %>% \n    filter(survey%in%c(\n      \"post_treatment_1\",\"post_treatment_2\",\"post_treatment_3\",\n      \"post_treatment_4\",\"post_treatment_5\"))\n\n# Select subset of post-treatment periods \npost_treat_subset <- counts_gpx %>% \n   filter(survey == \"post_treatment_4\")\n\nhead(post_treat_subset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  zoneid survey    waste_piles rain_0_48hrs rain_49_168hrs pre_count_avg pair_id\n   <dbl> <chr>           <dbl>        <dbl>          <dbl>         <dbl>   <dbl>\n1   1011 post_tre…          97         0              0.4           97      2021\n2   1012 post_tre…          12         0              0.4           12.5    2022\n3   1013 post_tre…          58         0              0.4           87.5    2022\n4   1014 post_tre…          88         0              0.4          110.     2021\n5   1015 post_tre…          53         0.04           0.36         110.     2017\n6   1016 post_tre…          18         0              0.4           23      2017\n# ℹ 1 more variable: treat <dbl>\n```\n\n\n:::\n:::\n\n\n\nNow that we got our data loaded in, lets take a look at what these variables mean.\n\n\n| Label | Description |\n|:---|:---|\n| **zoneid** | Zone or neighborhood ID: The observational unit ($N=44$) |\n| **waste_piles** | The outcome variable ($Y$): The number of waste pile burns recorded (Range: 5, 125) |\n| **treat** | The treatment assignment variable (0 = Control Group; 1 = Treatment Group) |\n| **rf_0_to_48_hours** | The rainfall estimated between 0 and 48 hours prior to the start of the audit, derived from NASA MEERA-2 corrected precipitation estimates (mm) |\n| **rf_49_to_168_hours** | The rainfall estimated between 49 and 168 hours prior to the start of the audit, derived from NASA MEERA-2 corrected precipitation estimates (mm) |\n| **pre_count_avg** | The average number of burnt piles in the pre-treatment audits, spread to zone level |\n| **pair_id** | The unique ID assigned to each pair of zones for assignment to treatment |\n\n\n### Model 1: Simple OLS (Ordinary Least Squares) estimator\n\nOLS estimator (specification):\n\n$$waste\\ piles =\\beta_0 + \\beta_1(treat) + \\epsilon$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_ols <- lm(\n    waste_piles ~ treat,\n    data = post_treat_subset)\n\nsumm(m1_ols, model.fit = FALSE) # model.fit = TRUE explains accuracy reports like R2\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> waste_piles </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 77.91 </td>\n   <td style=\"text-align:right;\"> 4.16 </td>\n   <td style=\"text-align:right;\"> 18.73 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -24.77 </td>\n   <td style=\"text-align:right;\"> 5.88 </td>\n   <td style=\"text-align:right;\"> -4.21 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\n\n**Interpretatation:**\n- interecept coeff: On average, the control group had 78 waste piles. \n\n- treat coeff: On average, the treatment groups had 25 less waste piles than the control group. \nor : The treatment reduced the average number of trash piles by approximately 25 piles \n\n- interecept SE: The true control average likely falls within 4.16 trash piles of 78. \n- treat SE: the true treatment effect likely falls within about +- 5.88 trash piles of -24.77\n\nt value (est/SE): \n- larger t value = stronger evidence the effect is real. \n\n##### Are we making reasonable assumptions?\n\n\nRemember questioning (and testing) assumptions is the heart of causal inference!We want to make sure our assumptions our reasonable. To do so, let'stake a quick look at our outcome variable `waste piles`, and then look at the normality of our residuals. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_treat_subset %>%\n  ggplot(aes(x = waste_piles)) +\n  geom_histogram(binwidth = 5, fill = \"blue\", color = \"white\", alpha = 0.7) +\n  labs(title = \"Histogram of Waste Piles\",\n    x = \"Waste Piles (counts)\",\n    y = \"Count\") +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week2_notes_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nWhile our data isn't a perfect bell curve, it also isn't severely skewed. Let's do another assumption check (normality of residuals) to help us decide if OLS is the right model for us. \n\nTo do so, we will make a QQ plot displaying residuals (y-axis) compared to the normal distribution (x-axis).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(m1_ols,  check = \"qq\" )\n```\n\n::: {.cell-output-display}\n![](week2_notes_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# de trended qq plot, where rather than y = x ( goal is a diag line), we want y - x = 0 (goal is a horizontal line). Makes errors easier to see\n```\n:::\n\nHmm, it doesn't seem like the OLS assumption, normality of residuals is a good fit for our data. Onto the next model! \n\n:::{.callout-tip}\n## Discussion\nSince we ruled OLS out, talk with your neighbor about another potential model to try. What kind of variable is our outcome variable? How might that inform what model we try next? \n:::\n\n\n\nWe can \"relax\" our assumptions by using a Generalized Linear model! Specifically, we will relax the assumption that the residuals are normally distributed. \n\n:::{.callout-warning}\n## Warning!\nWhen we relax an assumption and make our model more flexible, the statistics and interpretation become more complex! \n:::\n\nAs you discussed with your partner, our dependent variable, `waste_piles` is a count variable, not a continuous variable. Therefore, it's best we pick a model that explicitly accounts for count outcomes.  In walks the poisson regression model!\n\n### Model 2 : Poisson Generalized Linear Regression Model\n\nWe are going to assume Y follows a Poisson distribution with non negative integers (counts!). To do so, we need to think about the assumptions the Poisson regression makes. This model assumes that variance (dispersion) is proportional to the mean. Does our data match the theoretical distribution proposed? Let's check!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda_hat <- mean(post_treat_subset$waste_piles)\n\n# Generate theoretical poisson data\npoisson_curve <- tibble(\n  # Create a sequence of integers from 0 to max waste pile count\n  x = seq(0, max(post_treat_subset$waste_piles), by = 1),  \n  \n  # Calculate the probability (density) for each x value using the poisson formula\n  density = dpois(seq(0, max(post_treat_subset$waste_piles), by = 1), \n                  lambda = mean(post_treat_subset$waste_piles)) \n)\n\nggplot(post_treat_subset, aes(x = waste_piles)) +\n  # ..desnity .. resizes histogram bars so they can be compared to probability curve\n  geom_histogram(aes(y = ..density..), binwidth = 5, color = \"white\", fill = \"blue\", alpha = 0.7) + \n  # red line is showing us what poisson dist w averge of our data should look like\n  geom_line(data = poisson_curve, aes(x = x, y = density), color = \"red\", size = 1) +  # Poisson curve\n  # smoothed density line of our histogram \n  geom_density(color = \"green\", size = 1, adjust = 1.5) +  # KDE for a smoother curve\n  labs(\n    title = \"Plot of Empirical (Green) v. Theoretical (Red) Distributions\",\n    x = \"Waste Pile Counts\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week2_notes_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n Red is what our dist should look like for poisson. Green is our actual data. Not a great fit! Our variance is much larger than our mean (overdispersion).\n \n\n::: {.cell}\n\n```{.r .cell-code}\nm2_poisson <- glm(waste_piles ~ treat,\n                  family = poisson(link = \"log\"), # log bc it resticts outcome to positive values and changes model to be multiplicative ( percent change formula when we interpret)\n                  data = post_treat_subset)\n\nsumm(m2_poisson, model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> waste_piles </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> Generalized linear model </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Family </td>\n   <td style=\"text-align:right;\"> poisson </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Link </td>\n   <td style=\"text-align:right;\"> log </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> z val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 4.36 </td>\n   <td style=\"text-align:right;\"> 0.02 </td>\n   <td style=\"text-align:right;\"> 180.32 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -0.38 </td>\n   <td style=\"text-align:right;\"> 0.04 </td>\n   <td style=\"text-align:right;\"> -10.09 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: MLE</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nTo get percent change: (e^beta_1 -1) * 100\n- z test here bc variance is assumed/known from dist. IN OLS it is estimated from data but not known. \n- p value for int: H0: is log(control mean) = 0, alt: not euqal to zero. p = 0 means we reject null hypothesis that control has 1 waste pile\n\nInterpret: \n\nIntercept: On average, our control group has 78 (exp(4.36)) waste piles. \nTreat coeff: exp(-.038) = .68. .68 - 1  = -.32. This model estimates that treatment reduced waste burning  by 32% in treated neighborhoods.\n\n\n\nJust like OLS, we have some assumptions we need to check! \n\nWe first need to check for over dispersion. This is when our variance exceeds the mean. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_overdispersion(m2_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio =   5.873\n  Pearson's Chi-Squared = 246.680\n                p-value = < 0.001\n```\n\n\n:::\n:::\n\nIf our dispersion ratio was equal to 1, this would mean our mean is equal to our variance. Since our dispersion ratio is 5.873, and far greater than 1, we can see that our data has significant overdispersion. Poisson isn't the model for us! \n\n\n:::{.callout-tip}\n## Discussion\nSince we ruled OLS and Poisson Regression out, talk with your neighbor about another potential model to try. \n:::\n\n** Note, mabe negative binomial would be good here. Negative binomial assumes variance >mean\n\n### Model 3: Log- OLS Regression\n\nLog Linear Regression is an alternative way to model count outcomes using regular OLS. The only difference is that we are transforming our outcome variable to be on the log scale.\n\n\nWhy ? Helps to fix non normality issue! Prevents negative outcomes! percent change interpretation which is often better than direct counts ( more interpretable)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_log <- lm(\n    log(waste_piles) ~ treat,\n    data = post_treat_subset)\n\nsumm(m3_log, model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> log(waste_piles) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 4.31 </td>\n   <td style=\"text-align:right;\"> 0.08 </td>\n   <td style=\"text-align:right;\"> 51.97 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -0.42 </td>\n   <td style=\"text-align:right;\"> 0.12 </td>\n   <td style=\"text-align:right;\"> -3.57 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\ninterpretation: \n\nintercept: exp(4.31) = 74.44. There are 74 waste piles on average in the control group. \n\ntreat coeff: exp(-0.42) = .656. .657 - 1 = .35.  This model estimates that treatment reduced waste burning  by an average of 35% in treated neighborhoods.\n\n\n\n\nWe can compare our observed data to simulated data based on the model we just created (`m3_log`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_predictions(m3_log, verbose = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Minimum value of original data is not included in the\n  replicated data.\n  Model may not capture the variation of the data.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](week2_notes_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\ngenerating fake waste pile count data and using our model. \n\n\n### Model Recap \n\nLet's take a look at the three models we have created thus far and compare their results. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_summs(m1_ols, m2_poisson, m3_log,\n             model.names = c(\"OLS\",\"Poisson GLM\",\"Log(Outcome) OLS\"),\n             statistics = \"none\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\"  style=\"margin-left: auto; margin-right: auto;\">\n<col><col><col><col><thead>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\"></th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">OLS</th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">Poisson GLM</th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">Log(Outcome) OLS</th></tr>\n</thead>\n<tbody>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">(Intercept)</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">77.91 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">4.36 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">4.31 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(4.16)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.02)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">treat</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-24.77 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.38 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.42 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">(5.88)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">(0.04)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">(0.12)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" colspan=\"4\" style=\"border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\">*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</th></tr>\n</tbody>\n</table>\n\n```\n\n:::\n:::\n\n\n##### Let's do some quick math to compare treatment effect estimates\n\n$$\\% \\Delta Y = \\left( e^{\\beta_1} - 1 \\right) \\times 100$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate percent change in waste piles in each model:\n\nm1_change = (-24.77/77.91)*100   ## % change OLS = -31.8\nm2_change = (exp(-.38) - 1)*100  ## % change POIS = -31.6\nm3_change = (exp(-0.42) - 1)*100 ## % change LOG-OLS = -34.3\n```\n:::\n\n\nCould convert everything to trash pile counts, or to percentages. \n\nTo percentages: OLS -> percentage ( -24.77/77.91)\n\nTo trash pile counts: \n\n- poisson -> counts: exp(4.36), exp(-0.38)\n- log OLS -> counts: exp(4.31), exp(-0.42)\n\n\n:::{.callout-tip}\n## Treatment Estimate Check In\nInterpret the treatment estimate for the log OLS. \n:::\n\n**The treatment estimate for log-OLS can be interpret as follows:**\n\n> *The model estimated that the treatment group had, on average, a 34% reduction in waste piles relative to the control group.*\n\n\nLet's also take a look at the covariate balance table across treatment conditions.\n\n::: {.cell}\n\n```{.r .cell-code}\npost_treat_subset %>% \n    select(treat, waste_piles, pre_count_avg) %>% \n    tbl_summary(\n        by = treat,\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\")) %>% \n    modify_header(label ~ \"**Variable**\") %>%\n    modify_spanning_header(c(\"stat_1\", \"stat_2\") ~ \"**Treatment**\") \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xvrlkzxgma\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xvrlkzxgma table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xvrlkzxgma thead, #xvrlkzxgma tbody, #xvrlkzxgma tfoot, #xvrlkzxgma tr, #xvrlkzxgma td, #xvrlkzxgma th {\n  border-style: none;\n}\n\n#xvrlkzxgma p {\n  margin: 0;\n  padding: 0;\n}\n\n#xvrlkzxgma .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xvrlkzxgma .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xvrlkzxgma .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xvrlkzxgma .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xvrlkzxgma .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xvrlkzxgma .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xvrlkzxgma .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xvrlkzxgma .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xvrlkzxgma .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xvrlkzxgma .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xvrlkzxgma .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xvrlkzxgma .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xvrlkzxgma .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xvrlkzxgma .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xvrlkzxgma .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xvrlkzxgma .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xvrlkzxgma .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xvrlkzxgma .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xvrlkzxgma .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xvrlkzxgma .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xvrlkzxgma .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xvrlkzxgma .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xvrlkzxgma .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xvrlkzxgma .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xvrlkzxgma .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xvrlkzxgma .gt_left {\n  text-align: left;\n}\n\n#xvrlkzxgma .gt_center {\n  text-align: center;\n}\n\n#xvrlkzxgma .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xvrlkzxgma .gt_font_normal {\n  font-weight: normal;\n}\n\n#xvrlkzxgma .gt_font_bold {\n  font-weight: bold;\n}\n\n#xvrlkzxgma .gt_font_italic {\n  font-style: italic;\n}\n\n#xvrlkzxgma .gt_super {\n  font-size: 65%;\n}\n\n#xvrlkzxgma .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xvrlkzxgma .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xvrlkzxgma .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xvrlkzxgma .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xvrlkzxgma .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xvrlkzxgma .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xvrlkzxgma .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xvrlkzxgma .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xvrlkzxgma div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipWYXJpYWJsZSoq\"><span class='gt_from_md'><strong>Variable</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipUcmVhdG1lbnQqKg==\"><span class='gt_from_md'><strong>Treatment</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KiowKiogIApOID0gMjI=\"><span class='gt_from_md'><strong>0</strong><br />\nN = 22</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KioxKiogIApOID0gMjI=\"><span class='gt_from_md'><strong>1</strong><br />\nN = 22</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">waste_piles</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">78 (21)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">53 (18)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">pre_count_avg</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">94 (18)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">84 (26)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n:::{.callout-tip}\n## Discussion\nWhat potential issues do you notice with the `pre_count_avg` variable?\n:::\n\n\nThis takes us to our next model - controlling for `pre_count_avg`! \n\n### Model 4: Log- OLS Regression with a control variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4_control <- lm(\n    log(waste_piles) ~ \n        treat +\n        log(pre_count_avg), ## Add a control\n    data = post_treat_subset)\n\nsumm(m4_control, model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> log(waste_piles) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.47 </td>\n   <td style=\"text-align:right;\"> 0.35 </td>\n   <td style=\"text-align:right;\"> 1.34 </td>\n   <td style=\"text-align:right;\"> 0.19 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -0.27 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> -4.44 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> log(pre_count_avg) </td>\n   <td style=\"text-align:right;\"> 0.85 </td>\n   <td style=\"text-align:right;\"> 0.08 </td>\n   <td style=\"text-align:right;\"> 11.09 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: OLS</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nInterpretation: \n\n- Interecept: Our model estimates the expected waste piles for control areas at a pre-treatment average of 1 pile to be exp(0.47) ≈ 1.6 waste piles, though this is not statistically significant (p = 0.19).\n- treat: The treatment coefficient of -0.27 indicates that, after controlling for baseline waste levels, the treatment reduces waste piles by an average of 24%. \n- log(pre_count_aveage): The coefficient of 0.85 on log(pre_count_avg) means that a 1% increase in baseline waste ( pre count avg) is associated with a 0.85% increase in post-treatment waste.( in log - log models, the coefficient tells you the percent directly! ) \n\n\n\n\n\nLet's compare our two log OLS Regression Models. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_summs(m3_log, m4_control,\n             model.names = c(\"Log OLS Regression\",\"Log OLS Regression with a control variable\"),\n             statistics = \"none\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\"  style=\"margin-left: auto; margin-right: auto;\">\n<col><col><col><thead>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\"></th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">Log OLS Regression</th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">Log OLS Regression with a control variable</th></tr>\n</thead>\n<tbody>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">(Intercept)</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">4.31 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">0.47&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.08)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.35)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">treat</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.42 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.27 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.12)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">log(pre_count_avg)</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">0.85 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" colspan=\"3\" style=\"border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\">*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</th></tr>\n</tbody>\n</table>\n\n```\n\n:::\n:::\n\nWe have now controlled for `pre_count_avg`, but let's think about what other variables we could control for to improve our model. Other variables in our data include:\n\n| Label | Description |\n|:---|:---|\n| **rf_0_to_48_hours** | The rainfall estimated between 0 and 48 hours prior to the start of the audit, derived from NASA MEERA-2 corrected precipitation estimates (mm) |\n| **rf_49_to_168_hours** | The rainfall estimated between 49 and 168 hours prior to the start of the audit, derived from NASA MEERA-2 corrected precipitation estimates (mm) |\n\nThe environment doesn't sit still during our experiment, so let's control for it! We should account for events that might also affect trash burning during the treatment period (like rainfall)\n\nLet's start by looking at a covariate balance table for across treatment conditions for average rain events. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_treat_subset %>% \n    select(treat, waste_piles, rain_0_48hrs, rain_49_168hrs) %>% \n    tbl_summary(\n        by = treat,\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\")) %>% \n    modify_header(label ~ \"**Variable**\") %>% \n    modify_spanning_header(c(\"stat_1\", \"stat_2\") ~ \"**Treatment**\") \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kqwkhbqgzd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kqwkhbqgzd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kqwkhbqgzd thead, #kqwkhbqgzd tbody, #kqwkhbqgzd tfoot, #kqwkhbqgzd tr, #kqwkhbqgzd td, #kqwkhbqgzd th {\n  border-style: none;\n}\n\n#kqwkhbqgzd p {\n  margin: 0;\n  padding: 0;\n}\n\n#kqwkhbqgzd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kqwkhbqgzd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kqwkhbqgzd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kqwkhbqgzd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kqwkhbqgzd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kqwkhbqgzd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kqwkhbqgzd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kqwkhbqgzd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kqwkhbqgzd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kqwkhbqgzd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kqwkhbqgzd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kqwkhbqgzd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kqwkhbqgzd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kqwkhbqgzd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kqwkhbqgzd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqwkhbqgzd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kqwkhbqgzd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kqwkhbqgzd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kqwkhbqgzd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqwkhbqgzd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kqwkhbqgzd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqwkhbqgzd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kqwkhbqgzd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqwkhbqgzd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kqwkhbqgzd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kqwkhbqgzd .gt_left {\n  text-align: left;\n}\n\n#kqwkhbqgzd .gt_center {\n  text-align: center;\n}\n\n#kqwkhbqgzd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kqwkhbqgzd .gt_font_normal {\n  font-weight: normal;\n}\n\n#kqwkhbqgzd .gt_font_bold {\n  font-weight: bold;\n}\n\n#kqwkhbqgzd .gt_font_italic {\n  font-style: italic;\n}\n\n#kqwkhbqgzd .gt_super {\n  font-size: 65%;\n}\n\n#kqwkhbqgzd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kqwkhbqgzd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kqwkhbqgzd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kqwkhbqgzd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kqwkhbqgzd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kqwkhbqgzd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kqwkhbqgzd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kqwkhbqgzd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kqwkhbqgzd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipWYXJpYWJsZSoq\"><span class='gt_from_md'><strong>Variable</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipUcmVhdG1lbnQqKg==\"><span class='gt_from_md'><strong>Treatment</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KiowKiogIApOID0gMjI=\"><span class='gt_from_md'><strong>0</strong><br />\nN = 22</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KioxKiogIApOID0gMjI=\"><span class='gt_from_md'><strong>1</strong><br />\nN = 22</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">waste_piles</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">78 (21)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">53 (18)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">rain_0_48hrs</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0.18 (0.15)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.20 (0.16)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">rain_49_168hrs</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0.17 (0.17)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.17 (0.17)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm5_control2 <- lm(\n    log(waste_piles) ~ \n        treat +\n        log(pre_count_avg) +\n        rain_0_48hrs + rain_49_168hrs, # dont take log of rain bc rain can be 0, diff relationship -> additive makes more sense for rainfall( each mm of rain adds certain amount of waste)\n    data = post_treat_subset)\n\nsumm(m5_control2,\n     model.fit = FALSE,\n     robust = \"HC2\")  # Heteroskedasticity robust standard error adj.\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> log(waste_piles) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n   <td style=\"text-align:right;\"> 0.45 </td>\n   <td style=\"text-align:right;\"> 0.95 </td>\n   <td style=\"text-align:right;\"> 0.35 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -0.27 </td>\n   <td style=\"text-align:right;\"> 0.06 </td>\n   <td style=\"text-align:right;\"> -4.29 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> log(pre_count_avg) </td>\n   <td style=\"text-align:right;\"> 0.86 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 12.51 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> rain_0_48hrs </td>\n   <td style=\"text-align:right;\"> -0.02 </td>\n   <td style=\"text-align:right;\"> 0.85 </td>\n   <td style=\"text-align:right;\"> -0.03 </td>\n   <td style=\"text-align:right;\"> 0.98 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> rain_49_168hrs </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.79 </td>\n   <td style=\"text-align:right;\"> 0.09 </td>\n   <td style=\"text-align:right;\"> 0.93 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: Robust, type = HC2</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\n\nIntercept (0.43): Our model estimates the expected waste piles for control areas with a pre-treatment average of 1 pile and no rainfall to be exp(0.43) ≈ 1.5 waste piles, though this is not statistically significant (p = 0.35).\n\nTreatment coefficient (-0.27): The treatment coefficient of -0.27 indicates that, after controlling for baseline waste levels and rainfall, the treatment reduces waste piles by an average of 24% (p < 0.001).\n\nlog(pre_count_avg) coefficient (0.86): The coefficient of 0.86 on log(pre_count_avg) means that a 1% increase in baseline waste is associated with a 0.86% increase in post-treatment waste. \n\nrain_0_48hrs coefficient (-0.02): The coefficient of -0.02 suggests that each additional millimeter of rain in the 0-48 hours before measurement is associated with a 2% decrease in waste piles, though this effect is not statistically significant (p = 0.98).\n\nrain_49_168hrs coefficient (0.07): The coefficient of 0.07 suggests that each additional millimeter of rain in the 49-168 hours before measurement is associated with a 7% increase in waste piles, though this effect is not statistically significant (p = 0.93).\n\n\n\n\n\nNow that we have two fixed effects models, lets look at our results side by side. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_summs(m4_control, m5_control2, robust = \"HC2\",\n             model.names = c(\"M4 - Pre-treat\",\"M5 - Add Rain\"),\n             statistics = \"none\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\"  style=\"margin-left: auto; margin-right: auto;\">\n<col><col><col><thead>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\"></th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">M4 - Pre-treat</th><th class=\"huxtable-cell huxtable-header\" style=\"text-align: center;  border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;      font-weight: normal;\">M5 - Add Rain</th></tr>\n</thead>\n<tbody>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">(Intercept)</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">0.47&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;\">0.43&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.33)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.45)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">treat</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.27 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.27 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.06)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">log(pre_count_avg)</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">0.85 ***</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">0.86 ***</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.07)&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.07)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">rain_0_48hrs</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">-0.02&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">(0.85)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;      font-weight: normal;\">rain_49_168hrs</th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;\">0.07&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" style=\"border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;      font-weight: normal;\"></th><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td class=\"huxtable-cell\" style=\"text-align: right;  border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;\">(0.79)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th class=\"huxtable-cell huxtable-header\" colspan=\"3\" style=\"border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;      font-weight: normal;\">Standard errors are heteroskedasticity robust. *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</th></tr>\n</tbody>\n</table>\n\n```\n\n:::\n:::\n\n:::{.callout-tip}\n## Are neighborhoods independent?\nWe have another issue which may bias our treatment effect - the neighborhoods were paired together. We have to account for this paired data feature which is called clustered data. Clustered data violates the regression assumption that observations are independent and identically distributed (i.i.d). In-other-words, the data has within group dependencies, paired neighborhoods will likely be more similar than un-paired neighborhoods. \n:::\n\nLets account for these paired neighborhoods by adding a standard error adjustment based on our clusters. We can make this adjustment with the fixed effects model we just created (`m5_control2`) . \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumm(m5_control2,\n     robust = \"HC2\", # HC2 is a specific type of robust standard errors (bias-corrected)\n     cluster = \"pair_id\", # Add SE adj. based on pair-clusters\n     model.fit = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Observations </td>\n   <td style=\"text-align:right;\"> 44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Dependent variable </td>\n   <td style=\"text-align:right;\"> log(waste_piles) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Type </td>\n   <td style=\"text-align:right;\"> OLS linear regression </td>\n  </tr>\n</tbody>\n</table>  <table class=\"table table-striped table-hover table-condensed table-responsive\" style=\"width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:right;\"> Est. </th>\n   <th style=\"text-align:right;\"> S.E. </th>\n   <th style=\"text-align:right;\"> t val. </th>\n   <th style=\"text-align:right;\"> p </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n   <td style=\"text-align:right;\"> 0.49 </td>\n   <td style=\"text-align:right;\"> 0.88 </td>\n   <td style=\"text-align:right;\"> 0.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> treat </td>\n   <td style=\"text-align:right;\"> -0.27 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> -3.63 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> log(pre_count_avg) </td>\n   <td style=\"text-align:right;\"> 0.86 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 12.44 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> rain_0_48hrs </td>\n   <td style=\"text-align:right;\"> -0.02 </td>\n   <td style=\"text-align:right;\"> 0.97 </td>\n   <td style=\"text-align:right;\"> -0.03 </td>\n   <td style=\"text-align:right;\"> 0.98 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> rain_49_168hrs </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.94 </td>\n   <td style=\"text-align:right;\"> 0.07 </td>\n   <td style=\"text-align:right;\"> 0.94 </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Standard errors: Cluster-robust, type = HC2</td></tr></tfoot>\n</table>\n`````\n:::\n:::\n\nWhat are the key takeaways from this summary? Discuss with your neighbor! \n\n",
    "supporting": [
      "week2_notes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}