---
title: "Week 6: Instrumental Variable Design"
subtitle: ""
description: "February 10-13, 2026"
---


## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Lecture Materials {#lecture-materials}

| Lecture slides |  Resources |
|----------------|------------|
| [Lecture (TUES): Instrumental Variables - Part 1 ](https://drive.google.com/file/d/1XhHCQ9ciJEcyZqYWhzhcLBqVa5Wei6qE/view?usp=sharing){target="_blank"}  | [](){target="_blank"}  |  
| [Lecture (THURS): ](){target="_blank"}  | [](){target="_blank"}  | 
: {.hover .bordered tbl-colwidths="[50,25,25]"} 

<br>


## {{< fa clipboard-list title="a clipboard with a To Do list" >}} Pre-lab Prep {#pre-lab-prep} 

We will be using the `rnoaa` package to obtain our precipitation data. To do so, you need to request an API key. Enter your email at this [link](https://www.ncdc.noaa.gov/cdo-web/token), and an API key will be sent to you within ~ 2 minutes. 


## {{< fa laptop title="a laptop" >}} Lab Materials {#lab-materials}

| Lab Materials to Download | Lab Solution |
|----------------|------------|
| [Lab Materials to Download](https://downgit.github.io/#/home?url=https://github.com/annieradams/EDS241-Weekly-Labs/tree/main/week6){target="_blank"} | [Week 6 Lab](labs/week6.qmd){target="_blank"} |
: {.hover .bordered tbl-colwidths="[50,50]"}



## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}

| Assignment Type | Assignment Title                              | Date Assigned  | Date Due                   |
|-----------------|-----------------------------------------------|----------------|----------------------------|
| Assignment 3 | [Handout: HW3-Instrumental-Variables](assignments/HW3_IV_START.qmd){target="_blank"} , [Repository: HW3-IV-Stokes15](https://github.com/garberadamc/HW3-IV-Stokes15.git){target="_blank"} | 02/10 | 02/17 |
| Reading - *Mastering 'Metrics* | A&P: Chapter 3 (Instrumental Variables) | 02/09 | 02/11 |
| Reading - Focus on Instrumental Variable Analysis | [Stokes, 2015 ](https://drive.google.com/file/d/1y2Okzjq2EA43AW5JzCvFS8ecLpeP6NKh/view?usp=sharing){target="_blank"} | 02/09 | 02/11 |
: {.hover .bordered tbl-colwidths="[20,30,20,30]"} 