---
title: "Week 3: Difference-in-Difference"
subtitle: "[Thursday] Guest Speaker: Professor Mark Buntaine - Experimental Study Design"
description: "Week 3: January 20-23, 2026"
---


## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Lecture Materials {#lecture-materials}

| Lecture slides |   Resources |
|----------------|------------|
| [Lecture (TUES): Difference-in-Difference](https://drive.google.com/file/d/1QhnRsp2ik8SglQH4s3A8GZL0JblucrF_/view?usp=sharing){target="_blank"}  | [](){target="_blank"} ,  [](){target="_blank"} |  
| [Lecture (THURS): M. Buntaine Experiment](https://drive.google.com/file/d/1GwBA7AwnQU9gyWLGWtnGyOTUjRXAwL-k/view?usp=sharing){target="_blank"}  | [](){target="_blank"} ,  [](){target="_blank"} | 
: {.hover .bordered tbl-colwidths="[50,25,25]"} 

<br>

## {{< fa laptop title="a laptop" >}} Lab Materials {#lab-materials}

| Lab Materials to Download | Lab Solution |
|----------------|------------|
| [Week 3 Lab](https://downgit.github.io/#/home?url=https://github.com/annieradams/EDS241-Weekly-Labs/tree/main/week3) | [Week 3 Lab Solution](labs/week3.qmd) |
: {.hover .bordered tbl-colwidths="[50,50]"}



## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}

| Assignment Type | Assignment Title                              | Date Assigned  | Date Due                   |
|-----------------|-----------------------------------------------|----------------|----------------------------|
| Finish Reading Study | [Buntaine et al. (2024)](https://drive.google.com/file/d/1bvW40xguud2Y_bRnxwjCCZSmAZALgQTn/view){target="_blank"} , [ADD HERE -> Qs for Prof. Buntaine](https://docs.google.com/spreadsheets/d/1q0kQg3bUkkz5Kv4uTzRd8uEUsbfnavpAvBNHqwdCQgY/edit?usp=sharing){target="_blank"}  |  01/16 | 01/22 |
| Reading - Intro. to Natural Experiments  | [Larsen et al., 2019](https://drive.google.com/file/d/1r4KI5SwPpb41PTB_8C7NM9Rrz8RH4GBm/view?usp=drive_link){target="_blank"} |  01/16 | 01/22 |
| Reading - *Mastering 'Metrics* | A&P: Chapter 5 | 01/16 | 01/22 |

: {.hover .bordered tbl-colwidths="[20,30,20,30]"} 

<br>

::: {.left-text}

## {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} [**Extra resources**]{.teal-text .body-text-m}

- [Video - Interpreting regression coefficients & interactions - Assignment 1](https://drive.google.com/file/d/1ZYYDIodWKhrjzroVFGoBzN58LV5YT_Ol/view?usp=sharing)

:::

<br>

::: {.callout-tip}
# Assignment Submission and Rubric

- **Submission:** Submit assignments through `GradeScope`
- **Question-specific guide:** Each question has detailed grading criteria available on `GradeScope`. Be sure to review these guidelines before submitting your work!
- **General rubric outline:** For an overview of the grading criteria, refer to the [assignment rubric - general outline](https://docs.google.com/document/d/1JovgsTOiPCeUy5eehs9a4nPx5VoLlILV-1m_LBarmQU/edit?usp=sharing)
:::
