---
title: "Week 1: "
subtitle: "Introduction to Causal Inference"
description: "January 6-9, 2026"
---

::: {.callout-tip}
# Welcome to the page for all things Week 1!
:::

## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Lecture Materials {#lecture-materials}

| Lecture slides | Resources |
|----------------|------------|
| [Lecture 1 (TUE): Intro. to Casual Inference](https://drive.google.com/file/d/1kUUpk7ZLbjHTIaLMnb2in40EXwhAbsgD/view?usp=sharing){target="_blank"}   | |
|[Lecture 2 (THURS):Potenital Outcomes ](https://drive.google.com/file/d/1ZQvRgVOxu_QKmynCjb1vF1rKFrj1mwya/view?usp=sharing){target="_blank"}  | |

: {.hover .bordered tbl-colwidths="[50,25,25]"} 

## {{< fa laptop title="a laptop" >}} Lab Materials {#lab-materials}

| Lab Materials to Download | Lab Solution |
|----------------|------------|
| [Week 1 Lab](https://downgit.github.io/#/home?url=https://github.com/annieradams/EDS241-Weekly-Labs/tree/main/week1) | [Week 1 Lab Solution](labs/week1.qmd) |
: {.hover .bordered tbl-colwidths="[50,50]"}

## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}

| Assignment Type | Assignment Title                              | Date Assigned  | Date Due                   |
|-----------------|-----------------------------------------------|----------------|----------------------------|
| Assignment 1 | [Handout: HW1-LOBSTRS](https://garberadamc.github.io/project-site/hw1-lobstrs-eds241){target="_blank"} , [Repository: HW1-LOBSTRS](https://github.com/garberadamc/HW1-LOBSTRS-EDS241){target="_blank"} | 01/08 | 01/17 |
| Mini-Assignment | [Topics of Interest - Spreadsheet (Add Topic/Study Here)](https://docs.google.com/spreadsheets/d/1Y_yOCy_gOJyNjAejjpi1RRh1_trb2fWhlooQRlByu6E/edit?usp=sharing){target="_blank"} | 01/08 | 01/12 |
| Reading - *Mastering 'Metrics*  | A&P: [Introduction](https://drive.google.com/file/d/1-Q1s849GuEflv91CIEZMzUZM84IP8vmY/view){target="_blank"} & [Chapter 1](https://drive.google.com/file/d/1b0nRvm1cOCimmJuQrSp0gIorUjCdjppO/view){target="_blank"}  | 01/02 | 01/07 |
| Reading - Applied Policy Study | Pages 1-3: [Buntaine et al. (2024)](https://drive.google.com/file/d/1bvW40xguud2Y_bRnxwjCCZSmAZALgQTn/view){target="_blank"} , [Glossary of Econometrics & Statistics Terms](https://docs.google.com/document/d/1RIudsVcYhWGpqC-Uftk9UTz3PIq6stVyEpT44EPNgpE/edit?usp=sharing){target="_blank"}  | 01/02 | 01/07 |
| In Class (Thursday) | Reading Quiz | 01/08 | 01/08 |
| Week 2 - Reading - *Mastering 'Metrics*  | A&P: Chapter 2  | 01/08 | 01/15 |
| Week 2 - Reading - *Generalized Linear Models* | [Carruthers et al., 2008](https://drive.google.com/file/d/1msSVHclxUO-zMbZTLHqksvDel9m51h0R/view?usp=sharing){target="_blank"} | 01/13 | 01/13 |


: {.hover .bordered tbl-colwidths="[20,30,20,30]"} 

<br>

::: {.callout-tip}
# Assignment Submission and Rubric

- **Submission:** Submit assignments through `GradeScope`
- **Question-specific guide:** Each question has detailed grading criteria available on `GradeScope`. Be sure to review these guidelines before submitting your work!
- **General rubric outline:** For an overview of the grading criteria, refer to the [assignment rubric - general outline](https://docs.google.com/document/d/1JovgsTOiPCeUy5eehs9a4nPx5VoLlILV-1m_LBarmQU/edit?usp=sharing)
:::

## {{< fa comments title="two speech bubbles" >}} Extra Resources {#discussion-materials}

<br>

::: {.left-text}

[**Key Concepts (videos)**]{.teal-text .body-text-m}

These short videos that accompany *Mastering ’Metrics* are a great resource for Chapter-1. The style is a bit extra, but they explain the key concepts clearly. If any of these concepts are unclear, I strongly recommend watching them (they may be relevant to the reading quiz tomorrow):

- [Ceteris Paribus & Counterfactuals - 6 minutes](https://mru.org/courses/mastering-econometrics/ceteris-paribus)
- [Ommitted Variable Bias & Selection Bias - 9 minutes](https://mru.org/courses/mastering-econometrics/selection-bias)
- [Experimental Design & Random Assignment - 10 minutes](https://mru.org/courses/mastering-econometrics/introduction-randomized-trials)
- [How to Read Econometrics Papers - 12 minutes](https://mru.org/courses/mastering-econometrics/how-read-economics-research-papers-randomized-controlled-trials-rcts)

[**References**]{.teal-text .body-text-m}

- [Gelman, A., & Loken, E. (2013) ](https://drive.google.com/file/d/1Cx2fqgKDTzMQjXtyo4Cz2YK4dQQzpb4Z/view?usp=drive_link){target="_blank"}. *The garden of forking paths: Why multiple comparisons can be a problem, even when there is no “fishing expedition” or “p-hacking” and the research hypothesis was posited ahead of time.* Department of Statistics, Columbia University, 348(1-17), 3.
- [Buntaine, M. T., Komakech, P., & Shen, S. V. (2024)](https://drive.google.com/file/d/1bvW40xguud2Y_bRnxwjCCZSmAZALgQTn/view?usp=sharing). *Social competition drives collective action to reduce informal waste burning in Uganda.* Proceedings of the National Academy of Sciences, 121(23), e2319712121.


:::